# Generated by Django 4.1.1 on 2024-11-23 23:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_alter_directorgeneral_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='f_fabricacion',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2015, 1, 1))], verbose_name='F Fabricacion'),
        ),
    ]
